# permissions for end users to edit cronrestarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kchron
    app.kubernetes.io/managed-by: kustomize
  name: cronrestart-editor-role
rules:
- apiGroups:
  - resources.kchron.io
  resources:
  - cronrestarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.kchron.io
  resources:
  - cronrestarts/status
  verbs:
  - get
