---
apiVersion: resources.kchron.io/v1alpha1
kind: CronRestart
metadata:
  labels:
    app.kubernetes.io/name: kchron
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-ui
  namespace: default
spec:
  namespace: default
  resourceType: Deployment
  resources:
    - guestbook-ui
  cronSchedule: "*/3 * * * *"
---
apiVersion: resources.kchron.io/v1alpha1
kind: CronRestart
metadata:
  labels:
    app.kubernetes.io/name: kchron
    app.kubernetes.io/managed-by: kustomize
  name: app0-web
  namespace: dev
spec:
  namespace: dev
  resourceType: Deployment
  resources:
    - app0-web
  cronSchedule: "*/1 * * * *"
